module.exports = {
	SUCCESS: "SUCCESS",
	FAILURE: "FAILURE",
	ERROR : "ERROR",
	NOT_FOUND: "NOT_FOUND",
	CREATED_FAILURE : "CREATED_FAILURE",
	UPDATED_ERROR : "UPDATE_ERROR",
	PARAM_REQUIRE : "PARAM_REQUIRE",
	UNAUTHORIZED: "UNAUTHORIZED",
	DUPLICATE_USERNAME_OR_MAIL : "DUPLICATE_USERNAME_OR_MAIL",
	WRONG_PASSWORD_OR_USERNAME : "WRONG_PASSWORD_OR_USERNAME",
	USER_EXSITED : "USER_EXISTED"
};